import { StorageProvider } from './StorageProvider';
import { resolveUserStoragePath } from '../../utils/fileStorage';
import fs from 'fs';
import fsPromises from 'fs/promises';
import { AppError } from '../../utils/AppError';

export class LocalStorageProvider implements StorageProvider {
  async uploadFile(userId: string, fileId: string, buffer: Buffer, mimeType: string, originalName: string): Promise<string> {
    // Generate secure storage name based on fileId (since fileId is uniquely generated by us)
    const storedName = `${fileId}.bin`;
    
    // Resolve safe path
    const storagePath = await resolveUserStoragePath(userId, storedName);

    try {
      await fsPromises.writeFile(storagePath, buffer);
      return storagePath; // The local provider uses the absolute filesystem path as the provider ID
    } catch (error) {
      console.error('LocalStorageProvider Upload Error:', error);
      throw new AppError('Internal Server Error', 500);
    }
  }

  async downloadFile(providerFileId: string, res: NodeJS.WritableStream): Promise<void> {
    return new Promise((resolve, reject) => {
      // For LocalStorageProvider, providerFileId is the absolute storage path
      const fileStream = fs.createReadStream(providerFileId);
      
      fileStream.on('error', (err) => {
        console.error('LocalStorageProvider Stream Error:', err);
        reject(new AppError('Error reading file from storage', 500));
      });

      fileStream.pipe(res);
      
      fileStream.on('end', () => {
        resolve();
      });
    });
  }

  async deleteFile(providerFileId: string): Promise<void> {
    try {
      await fsPromises.unlink(providerFileId);
    } catch (error: any) {
      if (error.code !== 'ENOENT') {
        console.error(`Filesystem delete error for ${providerFileId}:`, error);
        throw new AppError('Error deleting file from storage', 500);
      }
    }
  }
}
